name: JSON check

on:
  pull_request_target:

jobs:
  json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: json-syntax-check
        uses: limitusus/json-syntax-check@v1
        with:
          pattern: "\\.json$"
          
      - name: Comment PR
        uses: unofficial-skills/actions-comment-pull-request@main
        with:
           message: |
                ✅ Welcome your PR has been validated successfully. 
           GITHUB_TOKEN: ${{ secrets.BOT }}       
          

  
  run-if-fail:
    if: ${{ always() && (needs.json.result=='failure') }}
    needs: [json]
    runs-on: ubuntu-latest
    steps:
    - name: Comment PR
      uses: unofficial-skills/actions-comment-pull-request@main
      with:
         message: |
              ❌ Storing of the JSON file has failed due to verification issues
         GITHUB_TOKEN: ${{ secrets.BOT }}
